// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoGpQWvf7SCCqYlwzyd8reyJrtNgH4uQk',
    appId: '1:768687735747:web:97e124085d25e581dff376',
    messagingSenderId: '768687735747',
    projectId: 'quickride-qr0103',
    authDomain: 'quickride-qr0103.firebaseapp.com',
    storageBucket: 'quickride-qr0103.appspot.com',
    measurementId: 'G-LM0GWDYYPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCroaJUq--7khmC_PXgWAIvIQQ3duMoRuI',
    appId: '1:768687735747:android:f935c2d15612b327dff376',
    messagingSenderId: '768687735747',
    projectId: 'quickride-qr0103',
    storageBucket: 'quickride-qr0103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6nhiXMuIb7cW4fzRODPFCpwMFBIjhLXk',
    appId: '1:768687735747:ios:db810e65c05051cfdff376',
    messagingSenderId: '768687735747',
    projectId: 'quickride-qr0103',
    storageBucket: 'quickride-qr0103.appspot.com',
    iosClientId: '768687735747-b5l593k62d6eus90qoddrgdabidlh4ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6nhiXMuIb7cW4fzRODPFCpwMFBIjhLXk',
    appId: '1:768687735747:ios:db810e65c05051cfdff376',
    messagingSenderId: '768687735747',
    projectId: 'quickride-qr0103',
    storageBucket: 'quickride-qr0103.appspot.com',
    iosClientId: '768687735747-b5l593k62d6eus90qoddrgdabidlh4ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickride',
  );
}
